
netty:
  resolver:
    dns:
      macos:
        native: false


spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3307/product_management
    username: user
    password: password
  logging:
    level:
      org.springframework.r2dbc.core: debug

  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
      timeout: 5000ms
